title: "JoÃ«l R. Langlois' Blog"
description: "Thoughts on software engineering, architecture, and problem-solving"
plugins:
  - jekyll-feed
  - jekyll-remote-theme
remote_theme: songzivong/dark-minima
